comentar el archivo de ya que se pausara el proyecto.. AutomationTest.yml

diff --git a/.github/workflows/AutomationTest.yml b/.github/workflows/AutomationTest.yml
--- a/.github/workflows/AutomationTest.yml
+++ b/.github/workflows/AutomationTest.yml
@@ -1,161 +1,162 @@
-name: TestAutomation
+# name: TestAutomation
 
-on:
-  push:
-    branches:
-      - master
-  pull_request:
-    branches:
-      - master
-  schedule:
-    - cron: "40 23 * * *"
-  workflow_dispatch: null
+# on:
+#   push:
+#     branches:
+#       - master
+#   pull_request:
+#     branches:
+#       - master
+#   schedule:
+#     - cron: "40 23 * * *"
+#   workflow_dispatch: null
 
-jobs:
-  HourReportingAutomation:
-    # No se ejecuta si el secret está en "true" 
-    runs-on: ubuntu-latest
-    steps:
-      # No se ejecuta si el secret está en "true" 
-      - name: Check if workflow is paused
-        run: |
-          if [ "${{ secrets.WORKFLOW_PAUSED }}" == "true" ]; then
-          echo "🚨 Workflow pausado. Saliendo..."
-          exit 1
-          fi
-      - name: Checkout repository
-        uses: actions/checkout@v4
+# jobs:
+#   HourReportingAutomation:
+#     # No se ejecuta si el secret está en "true" 
+#     runs-on: ubuntu-latest
+#     steps:
+#       # No se ejecuta si el secret está en "true" 
+#       - name: Check if workflow is paused
+#         run: |
+#           if [ "${{ secrets.WORKFLOW_PAUSED }}" == "true" ]; then
+#           echo "🚨 Workflow pausado. Saliendo..."
+#           exit 1
+#           fi
+#       - name: Checkout repository
+#         uses: actions/checkout@v4
         
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: "20"
+#       - name: Setup Node.js
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: "20"
           
-      - name: Install dependencies
-        run: npm install
+#       - name: Install dependencies
+#         run: npm install
         
-      - name: Install Playwright browsers
-        run: npx playwright install
+#       - name: Install Playwright browsers
+#         run: npx playwright install
 
-      - name: Capture Start Time
-        id: start_time
-        run: echo "START_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
+#       - name: Capture Start Time
+#         id: start_time
+#         run: echo "START_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
         
-      - name: Run Playwright tests
-        run: npx playwright test
-        env:
-          CI: true
-          REDMINE_USERNAME: ${{ secrets.REDMINE_USERNAME }}
-          REDMINE_PASSWORD: ${{ secrets.REDMINE_PASSWORD }}
-          OPERACION_USERNAME: ${{ secrets.OPERACION_USERNAME }}
-          OPERACION_PASSWORD: ${{ secrets.OPERACION_PASSWORD }}
+#       - name: Run Playwright tests
+#         run: npx playwright test
+#         env:
+#           CI: true
+#           REDMINE_USERNAME: ${{ secrets.REDMINE_USERNAME }}
+#           REDMINE_PASSWORD: ${{ secrets.REDMINE_PASSWORD }}
+#           OPERACION_USERNAME: ${{ secrets.OPERACION_USERNAME }}
+#           OPERACION_PASSWORD: ${{ secrets.OPERACION_PASSWORD }}
 
-      - name: Capture End Time and Duration
-        id: end_time
-        run: |
-          END_TIME=$(date +'%Y-%m-%d %H:%M:%S')
-          START_TIME="${{ env.START_TIME }}"
-          DURATION=$(echo $(date -d "$END_TIME" +%s) - $(date -d "$START_TIME" +%s) | bc)
-          echo "END_TIME=$END_TIME" >> $GITHUB_ENV
-          echo "DURATION=$DURATION" >> $GITHUB_ENV
+#       - name: Capture End Time and Duration
+#         id: end_time
+#         run: |
+#           END_TIME=$(date +'%Y-%m-%d %H:%M:%S')
+#           START_TIME="${{ env.START_TIME }}"
+#           DURATION=$(echo $(date -d "$END_TIME" +%s) - $(date -d "$START_TIME" +%s) | bc)
+#           echo "END_TIME=$END_TIME" >> $GITHUB_ENV
+#           echo "DURATION=$DURATION" >> $GITHUB_ENV
 
-      - name: Upload Playwright report
-        if: always()  # Siempre se ejecuta, incluso si los tests fallan
-        uses: actions/upload-artifact@v4
-        with:
-          name: playwright-report
-          path: playwright-report/
+#       - name: Upload Playwright report
+#         if: always()  # Siempre se ejecuta, incluso si los tests fallan
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: playwright-report
+#           path: playwright-report/
 
-      # Enviar correo si los tests son exitosos
-      - name: Send success email
-        if: success()
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 587
-          username: ${{ secrets.EMAIL_USERNAME }}
-          password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: "✅ Reporte de Horas: El registro de horas fue Completado Exitosamente"
-          to: ${{ secrets.GMAIL_RECIPIENT }}
-          from: ${{ secrets.EMAIL_USERNAME }}
-          body: |
-            Buenas tardes, John,
+#       # Enviar correo si los tests son exitosos
+#       - name: Send success email
+#         if: success()
+#         uses: dawidd6/action-send-mail@v3
+#         with:
+#           server_address: smtp.gmail.com
+#           server_port: 587
+#           username: ${{ secrets.EMAIL_USERNAME }}
+#           password: ${{ secrets.EMAIL_PASSWORD }}
+#           subject: "✅ Reporte de Horas: El registro de horas fue Completado Exitosamente"
+#           to: ${{ secrets.GMAIL_RECIPIENT }}
+#           from: ${{ secrets.EMAIL_USERNAME }}
+#           body: |
+#             Buenas tardes, John,
   
-            Nos complace informarle que su reporte diario en Redmine/Operaciones SQA se ha ejecutado con éxito.
+#             Nos complace informarle que su reporte diario en Redmine/Operaciones SQA se ha ejecutado con éxito.
 
   
-               Resumen del Proceso
-            - Plataforma: Redmine/Operaciones SQA
-            - Fecha de Ejecución: ${{ env.START_TIME }}
-            - Hora de Finalización: ${{ env.END_TIME }}
-            - Estado General: ✅ Exitoso.
-            - Duración del Proceso: ${{ env.DURATION }} Segundos
+#                Resumen del Proceso
+#             - Plataforma: Redmine/Operaciones SQA
+#             - Fecha de Ejecución: ${{ env.START_TIME }}
+#             - Hora de Finalización: ${{ env.END_TIME }}
+#             - Estado General: ✅ Exitoso.
+#             - Duración del Proceso: ${{ env.DURATION }} Segundos
   
-                Detalles del Proceso
-            - Todos los pasos fueron completados con éxito.
-            - Sin errores ni interrupciones durante la ejecución.
-            - Reporte Generado: Sí.
+#                 Detalles del Proceso
+#             - Todos los pasos fueron completados con éxito.
+#             - Sin errores ni interrupciones durante la ejecución.
+#             - Reporte Generado: Sí.
   
-                Próximos Pasos
-            - El reporte está disponible para su revisión detallada.
-            - Si necesita realizar alguna acción adicional o tiene dudas, por favor, no dude en contactarnos.
+#                 Próximos Pasos
+#             - El reporte está disponible para su revisión detallada.
+#             - Si necesita realizar alguna acción adicional o tiene dudas, por favor, no dude en contactarnos.
   
-            Gracias por confiar en nuestro servicio, John.  
-            Estamos comprometidos en ofrecerle un proceso continuo y eficiente. 
+#             Gracias por confiar en nuestro servicio, John.  
+#             Estamos comprometidos en ofrecerle un proceso continuo y eficiente. 
   
-            Saludos cordiales,  
-            _Equipo de Automatización y Reportes_  
+#             Saludos cordiales,  
+#             _Equipo de Automatización y Reportes_  
 
             
-            Nota: Este mensaje fue generado automáticamente por nuestro sistema. Si tiene preguntas, no dude en contactarnos.
-         ## attachments: playwright-report/index.html  # Asegúrate de que este archivo exista
-          attachments: |
-                   [
-                       { "file": "playwright-report/screenshots/screenshot.png", "inline": true, "cid": "screenshot" }
-                   ]
+#             Nota: Este mensaje fue generado automáticamente por nuestro sistema. Si tiene preguntas, no dude en contactarnos.
+#          ## attachments: playwright-report/index.html  # Asegúrate de que este archivo exista
+#           attachments: |
+#                    [
+#                        { "file": "playwright-report/screenshots/screenshot.png", "inline": true, "cid": "screenshot" }
+#                    ]
 
-      # Enviar correo si los tests fallan
-      - name: Send failure email
-        if: failure()
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 587
-          username: ${{ secrets.EMAIL_USERNAME }}
-          password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: "🚨 Alerta Se Presentaros Fallos : El registro de horas Fallaron Durante la Ejecución"
-          to: ${{ secrets.GMAIL_RECIPIENT }}
-          from: ${{ secrets.EMAIL_USERNAME }}
-          body: |
-            Buenas tardes, John,
+#       # Enviar correo si los tests fallan
+#       - name: Send failure email
+#         if: failure()
+#         uses: dawidd6/action-send-mail@v3
+#         with:
+#           server_address: smtp.gmail.com
+#           server_port: 587
+#           username: ${{ secrets.EMAIL_USERNAME }}
+#           password: ${{ secrets.EMAIL_PASSWORD }}
+#           subject: "🚨 Alerta Se Presentaros Fallos : El registro de horas Fallaron Durante la Ejecución"
+#           to: ${{ secrets.GMAIL_RECIPIENT }}
+#           from: ${{ secrets.EMAIL_USERNAME }}
+#           body: |
+#             Buenas tardes, John,
   
-            Queremos informarle que durante la ejecución del reporte diario en Redmine/Operaciones SQA, se detectaron problemas que impidieron completar el proceso con éxito.  
+#             Queremos informarle que durante la ejecución del reporte diario en Redmine/Operaciones SQA, se detectaron problemas que impidieron completar el proceso con éxito.  
   
-                Resumen del Proceso
-            - Plataforma: Redmine/Operaciones SQA
-            - Fecha de Ejecución: ${{ env.START_TIME }}
-            - Hora de Finalización: ${{ env.END_TIME }}
-            - Estado General: ❌ Fallido.
-            - Duración del Proceso:  ${{ env.DURATION }} Segundos
+#                 Resumen del Proceso
+#             - Plataforma: Redmine/Operaciones SQA
+#             - Fecha de Ejecución: ${{ env.START_TIME }}
+#             - Hora de Finalización: ${{ env.END_TIME }}
+#             - Estado General: ❌ Fallido.
+#             - Duración del Proceso:  ${{ env.DURATION }} Segundos
   
-                Detalles del Problema
-            - Descripción del Error: [Mensaje de error específico si está disponible o “Problema no especificado”].
-            - Paso Afectado: [Paso o módulo afectado en Redmine/Operaciones SQA].
-            - Reporte Generado: Sí.
+#                 Detalles del Problema
+#             - Descripción del Error: [Mensaje de error específico si está disponible o “Problema no especificado”].
+#             - Paso Afectado: [Paso o módulo afectado en Redmine/Operaciones SQA].
+#             - Reporte Generado: Sí.
   
-            Nuestro equipo ya está investigando el incidente para identificar la causa raíz y aplicar una solución lo más pronto posible.  
+#             Nuestro equipo ya está investigando el incidente para identificar la causa raíz y aplicar una solución lo más pronto posible.  
   
-            Recomendaciones
-            - Le sugerimos no realizar acciones manuales en los módulos afectados hasta que le confirmemos que el problema ha sido resuelto.  
-            - Si necesita asistencia inmediata, puede responder este correo o contactarnos directamente.
+#             Recomendaciones
+#             - Le sugerimos no realizar acciones manuales en los módulos afectados hasta que le confirmemos que el problema ha sido resuelto.  
+#             - Si necesita asistencia inmediata, puede responder este correo o contactarnos directamente.
   
-            Agradecemos su comprensión, John.  
-            Lamentamos los inconvenientes ocasionados y seguimos trabajando para restablecer el servicio a la brevedad.
+#             Agradecemos su comprensión, John.  
+#             Lamentamos los inconvenientes ocasionados y seguimos trabajando para restablecer el servicio a la brevedad.
   
-            Saludos cordiales,  
-            _Equipo de Automatización y Reportes_  
+#             Saludos cordiales,  
+#             _Equipo de Automatización y Reportes_  
   
-            ---
-            Nota: Este mensaje fue generado automáticamente por nuestro sistema. Si tiene preguntas, no dude en contactarnos.
+#             ---
+#             Nota: Este mensaje fue generado automáticamente por nuestro sistema. Si tiene preguntas, no dude en contactarnos.
   
-          attachments: playwright-report/index.html  # Asegúrate de que este archivo exista
+#           attachments: playwright-report/index.html  # Asegúrate de que este archivo exista
+
